import Head from 'next/head'
import { Profile } from '../../container/profile'

export default function ProfileView() {
  return (
    <div >
      <Head>
        <title>Delibery de Historia </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Profile />
    </div>
  )
}
