import Head from 'next/head'
import Image from 'next/image'
// import { History } from '../container/history'
// import { Home } from '../container/Home'

export default function HomeView() {
  return (
    <div >
      <Head>
        <title>Delibery de Historia </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <History /> */}
    </div>
  )
}
