import { useQuery } from '@apollo/client'
import Head from 'next/head'
import Image from 'next/image'
import { Historial } from '../container/history'
import { Home } from '../container/Home'
import { GET_ALL_FAV_STORE } from '../container/profile/queries'
import styles from '../styles/Home.module.css'

export default function HomeView() {
  const { data: dataFav } = useQuery(GET_ALL_FAV_STORE)
  return (
    <div >
      <Head>
        <title>Delibery de Historia </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Historial dataFav={dataFav?.getFavorite || []} />
    </div>
  )
}
