import Head from 'next/head'
import Image from 'next/image'
import { Home } from '../container/Home'
import styles from '../styles/Home.module.css'

export default function HomeView() {
  return (
    <div >
      <Head>
        <title>Delibery de comida  cambio de kerlyn </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Home />
    </div>
  )
}
