import Head from 'next/head'
import { Home } from '../container/Home'
import { EmptyLayout } from './_app'

export default function HomeView() {
  return (
    <div >
      <Head>
        <title>Delibery </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Home />
    </div>
  )
}

HomeView.Layout = EmptyLayout
