import Head from 'next/head'
import Image from 'next/image'
import { RestaurantProfile } from '../../../../container/RestaurantProfile'

export default function HomeView() {
  return (
    <div >
      <Head>
        <title>Hola mundo </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <RestaurantProfile />
    </div>
  )
}
