import Head from 'next/head'
import Image from 'next/image'
import { useQuery } from '@apollo/client'
import styles from '../../styles/Home.module.css'
import { GET_ONE_STORE } from '../../container/queries'
import { Restaurant } from '../../container/restaurantes'
import { useContext } from 'react'
import { Context } from '../../context'
import { PromosBanner } from '../../container/restaurantes/PromosBanner'
import { Section } from '../../container/restaurantes/styled'
import { ListRestaurant } from '../../container/restaurantes/restaurant'

export default function RestaurantHome() {
  const { data } = useQuery(GET_ONE_STORE)
  const { setAlertBox, dispatch, state_product_card } = useContext(Context)
  console.log(state_product_card, 'HOLA ERRO');
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Section>
        <PromosBanner />
      </Section>
      <Section>
        <Restaurant />
      </Section>
      <Section>
        <ListRestaurant />
      </Section>
    </div>
  )
}
