import Head from 'next/head'
import Image from 'next/image'
import { gql, useLazyQuery, useQuery, useSubscription } from '@apollo/client'
import styles from '../../styles/Home.module.css'
import { GET_ONE_STORE } from '../../container/queries'
import { Restaurant } from '../../container/restaurantes'
import { useContext, useEffect, useState } from 'react'
import { Context } from '../../context'
import { PromosBanner } from '../../container/restaurantes/PromosBanner'
import { Section } from '../../container/restaurantes/styled'
import { ListRestaurant } from '../../container/restaurantes/restaurant'
import { GET_ALL_COUNTRIES } from '../../gql/Location'
import withSession from '../../apollo/session'
import { decodeToken } from '../../utils'
import { GET_ALL_RESTAURANT } from '../../container/restaurantes/queries'
import { GET_MESSAGES } from '../../gql/test'

export default function RestaurantHome() {
  const { data } = useQuery(GET_ONE_STORE)
  const { data: dataEy } = useQuery(GET_ALL_COUNTRIES)
  const { data: dataM } = useQuery(GET_MESSAGES, {
    context: { clientName: "subscriptions" }
  });
  console.log(dataM, 'hola')
  const NEW_MESSAGE = gql`
  subscription {
  numberIncremented
}
  `
  const [dataStore, setData] = useState([])
  const [showMore, setShowMore] = useState(100)
  const [getAllStoreInStore, { data: dataListStore }] = useLazyQuery(GET_ALL_RESTAURANT)
  /* Filtro  */
  const [searchFilter, setSearchFilter] = useState({ gender: [], desc: [], speciality: [] })
  const [filter, setFilter] = useState({ gender: [], desc: [], speciality: [] })
  useEffect(() => {
    // setData([data?.getAllStoreInStore])
  }, [searchFilter])
  useEffect(() => {
    getAllStoreInStore({ variables: { max: showMore } })
  }, [searchFilter, showMore])
  // ********************************LIST RESTAURANT FIN********************************
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Section>
        <PromosBanner />
      </Section>
      <Section>
        <Restaurant />
      </Section>
      <Section>
        <ListRestaurant
          data={dataListStore?.getAllStoreInStore || []}
        />
      </Section>
    </div>
  )
}

export const getServerSideProps = withSession(async function ({ req, res }) {
  const user = req?.session?.get('user')
  if (!user) {
    res.setHeader('location', '/entrar')
    res.statusCode = 302
    res.end()
    return { props: {} }
  }
  const { token } = user || {}
  const data = decodeToken(token)
  const { id } = data || {}
  if (!req.cookies[process.env.SESSION_NAME]) return { redirect: { destination: '/entrar' } }

  return {
    props: {}
  }
}
)
