import Head from 'next/head'
import Image from 'next/image'
import { useQuery } from '@apollo/client'
import styles from '../../styles/Home.module.css'
import { GET_ONE_STORE } from '../../container/queries'

export default function Home() {
  const { data } = useQuery(GET_ONE_STORE)
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  )
}
