import withSession from 'apollo/session';
import { Activity } from 'container/Activity';
import { LocationName } from 'hooks/useLocationName'
import Head from 'next/head'
export default function Home() {
  return (
    <div >
      <Head>
        <title>{process.env.NEXT_NAME_APP}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LocationName />
      <Activity />
    </div>
  )
}


export const getServerSideProps = withSession(async function ({ req, res }) {
  const user = req?.session?.get('user')
  if (!user) {
    res.setHeader('location', '/')
    res.statusCode = 302
    res.end()
    return { props: {} }
  }
  if (!req.cookies[process.env.SESSION_NAME]) return { redirect: { destination: '/' } }

  return {
    props: {}
  }
}
)
