import { useQuery } from '@apollo/client'
import withSession from 'apollo/session'
import { PaymentCard } from 'container/payment'
import Head from 'next/head'
import { useEffect, useState } from 'react'

export default function PayView() {
  return (
    <div >
      <Head>
        <title>Delibery de Historia </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PaymentCard 
      />
    </div>
  )
}

export const getServerSideProps = withSession(async function ({ req, res }) {
  const user = req?.session?.get('user')
  if (!user) {
    res.setHeader('location', '/entrar')
    res.statusCode = 302
    res.end()
    return { props: {} }
  }
  if (!req.cookies[process.env.SESSION_NAME]) return { redirect: { destination: '/entrar' } }

  return {
    props: {
    }
  }
}
)
