import { useEffect } from 'react'
import Image from 'next/image'
import { getSession, signOut, signIn, getProviders } from 'next-auth/react'
import styles from '../styles/Home.module.css'
import Head from 'next/head'
import { useState } from 'react'
import { Login } from 'container'


export default function Home({ session }) {
//   const { user } = session || {}
//   const { name, image } = user || {}
  const [providers, setProviders] = useState([])
   useEffect(() => {
    (async () => {
      const providers = await getProviders();
      setProviders(providers);
      console.log(providers)
    })();
  }, []);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <button onClick={() => signOut()}>Close</button>       */}
      <Login providers={providers}/>
    </div>
  )
}

export const getServerSideProps = async (context) => {
  const session = await getSession(context)
  if (!session) return {
    redirect: {
      permanent: false,
      destination: '/entrar'
    }
  }

  return {
    props: {
      session: session
    }
  }
}
