import withSession from 'apollo/session'
import Head from 'next/head'
import Image from 'next/image'
import { CheckoutFinalizar } from '../../../container/checkoutFinalizar'

export default function procesoFinalView() {
  return (
    <div >
      <Head>
        <title>Delibery Proceso  final </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CheckoutFinalizar />

    </div>
  )
}

export const getServerSideProps = withSession(async function ({ req, res }) {
  const user = req?.session?.get('user')
  if (!user) {
    res.setHeader('location', '/entrar')
    res.statusCode = 302
    res.end()
    return { props: {} }
  }
  if (!req.cookies[process.env.SESSION_NAME]) return { redirect: { destination: '/entrar' } }

  return {
    props: {
    }
  }
}
)
