import { useLazyQuery, useMutation } from '@apollo/client'
import Head from 'next/head'
import Image from 'next/image'
import { useRouter } from 'next/router'
import { useEffect, useState } from 'react'
import { ConfirmCheckout } from '../../../../container/ConfirmCheckout'
import { CREATE_ONE_STORE_PEDIDO } from '../../../../container/confirmCheckout/queries'
import { GET_ONE_PRODUCTS_FOOD } from '../../../../container/queries'

export default function procesoConfirmView() {
  const location = useRouter()
  const [payMethod, setPayMethod] = useState(1)
  const [recoger, setRecoger] = useState(1)
  const { code, idstore, pid } = location.query
  const [productFoodsOne, { data: dataOneProduct }] = useLazyQuery(GET_ONE_PRODUCTS_FOOD)
  useEffect(() => {
    productFoodsOne({ variables: { pid: pid } })
  }, [code, idstore, pid])
  const [createOnePedidoStore] = useMutation(CREATE_ONE_STORE_PEDIDO, {
    onError: (err) => console.error(err)
  })
  const handleSubmitPedido = async e => {
    await createOnePedidoStore({
      variables: {
        input: {
          id: 'MjE3NjcxMDUxODgxMjEzMTYwMA==',
          pId: pid,
          idStore: idstore,
          pPStateP: 1,
          pDatMod: 1,
          unidProducts: 1,
          pCodeRef: code,
          payMethodPState: payMethod,
          pPRecoger: recoger,
        }
      }
    })
  }
  return (
    <div >
      <Head>
        <title>Delibery pedido </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ConfirmCheckout
        dataOneProduct={dataOneProduct?.productFoodsOne || {}}
        idstore={idstore}
        code={code}
        handleSubmitPedido={handleSubmitPedido}
        pid={pid}
      />
    </div>
  )
}
