import Head from 'next/head'
import { Categories } from 'container/categorias'
export default function View() {
  return (
    <div >
      <Head>
        <title>Delibery de Historia </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Categories />
    </div>
  )
}
