import Head from 'next/head'
import Image from 'next/image'
import { Checkout } from '../../container/checkout'

export default function procesoView() {
  return (
    <div >
      <Head>
        <title>Delibery Proceso  </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Checkout 
      
      />
    </div>
  )
}
