import withSession from 'apollo/session'
import Head from 'next/head'
import Image from 'next/image'
import { useContext } from 'react'
import { Checkout } from '../../container/checkout'
import { Context } from '../../context'

export default function procesoView() {
    const { setAlertBox, setCountItemProduct, locationStr, setModalLocation } = useContext(Context)
  return (
    <div >
      <Head>
        <title>Delibery Proceso  </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Checkout 
        setAlertBox={setAlertBox} 
        setModalLocation={setModalLocation} 
        locationStr={locationStr} 
        setCountItemProduct={setCountItemProduct}
      />
    </div>
  )
}

// export const getServerSideProps = withSession(async function ({ req, res }) {
//   const user = req?.session?.get('user')
//   if (!user) {
//     res.setHeader('location', '/entrar')
//     res.statusCode = 302
//     res.end()
//     return { props: {} }
//   }
//   if (!req.cookies[process.env.SESSION_NAME]) return { redirect: { destination: '/entrar' } }

//   return {
//     props: {
//     }
//   }
// }
// )
