import Head from 'next/head'
import Image from 'next/image'
import { useContext } from 'react'
import { Checkout } from '../../container/checkout'
import { Context } from '../../context'

export default function procesoView() {
    const { setAlertBox, setCountItemProduct } = useContext(Context)
  return (
    <div >
      <Head>
        <title>Delibery Proceso  </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Checkout 
      setAlertBox={setAlertBox} 
      setCountItemProduct={setCountItemProduct}
      />
    </div>
  )
}
