import { Login } from 'container/login';
import Head from 'next/head'
import axios from 'axios';
import { EmptyLayout } from './_app';
export default function Home() {

  const onChange = async (formData) => {
    const config = {
      headers: { 'content-type': 'multipart/form-data' },
      onUploadProgress: (event) => {
        console.log(`Current progress:`, Math.round((event.loaded * 100) / event.total));
      },
    };
    const response = await axios.post('/api/uploads', formData, config);
    console.log('response', response.data);
  }
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Login
        label="Upload Single File"
        uploadFileName="theFiles"
        onChange={onChange}
      />
    </div>
  )
}

Home.Layout = EmptyLayout
